# -*- coding: UTF-8 -*-

TABLE_DES_STATEMENTS = """SELECT T.COLUMN_ID,\
       T.COLUMN_NAME AS COL_NAME,\
       T.DATA_TYPE || CASE WHEN T.DATA_PRECISION IS NOT NULL THEN\
          '(' || T.DATA_PRECISION ||\
          DECODE(T.DATA_SCALE, 0, '', NULL, '', ',' || T.DATA_SCALE) || ')'\
         ELSE\
          NULL\
       END AS DATA_TYPE,\
       T.NULLABLE,\
       NULL AS DEFAULT_EXPRESSION,\
       TRIM(A.COMMENTS) AS COMMENTS\
  FROM ALL_TAB_COLUMNS T\
  LEFT JOIN ALL_COL_COMMENTS A\
    ON A.OWNER = T.OWNER\
   AND A.TABLE_NAME = T.TABLE_NAME\
   AND A.COLUMN_NAME = T.COLUMN_NAME\
 WHERE T.OWNER = :OWNER\
   AND T.TABLE_NAME= :TABLE_NAME\
 ORDER BY T.COLUMN_ID ASC """

TABLE_DES_STATEMENTS_2 = """SELECT T.COLUMN_ID,\
       T.COLUMN_NAME AS COL_NAME,\
       T.DATA_TYPE || CASE WHEN T.DATA_PRECISION IS NOT NULL THEN\
          '(' || T.DATA_PRECISION ||\
          DECODE(T.DATA_SCALE, 0, '', NULL, '', ',' || T.DATA_SCALE) || ')'\
         ELSE\
          NULL\
       END AS DATA_TYPE,\
       T.NULLABLE,\
       NULL AS DEFAULT_EXPRESSION,\
       TRIM(A.COMMENTS) AS COMMENTS\
  FROM ALL_TAB_COLUMNS T\
  LEFT JOIN ALL_COL_COMMENTS A\
    ON A.OWNER = T.OWNER\
   AND A.TABLE_NAME = T.TABLE_NAME\
   AND A.COLUMN_NAME = T.COLUMN_NAME\
 WHERE T.OWNER = %s \
   AND T.TABLE_NAME= %s \
 ORDER BY T.COLUMN_ID ASC """

TABLE_DES_STATEMENTS_3 = """SELECT T.COLUMN_ID,\
       T.COLUMN_NAME AS COL_NAME,\
       T.DATA_TYPE || CASE WHEN T.DATA_PRECISION IS NOT NULL THEN\
          '(' || T.DATA_PRECISION ||\
          DECODE(T.DATA_SCALE, 0, '', NULL, '', ',' || T.DATA_SCALE) || ')'\
         ELSE\
          NULL\
       END AS DATA_TYPE,\
       T.NULLABLE,\
       NULL AS DEFAULT_EXPRESSION,\
       TRIM(A.COMMENTS) AS COMMENTS\
  FROM ALL_TAB_COLUMNS T\
  LEFT JOIN ALL_COL_COMMENTS A\
    ON A.OWNER = T.OWNER\
   AND A.TABLE_NAME = T.TABLE_NAME\
   AND A.COLUMN_NAME = T.COLUMN_NAME\
 WHERE T.OWNER = :1\
   AND T.TABLE_NAME= :2\
 ORDER BY T.COLUMN_ID"""

TAB_COMMENT_STATEMENTS = """
SELECT COUNT(*) FROM ALL_TAB_COMMENTS T\
   WHERE T.OWNER = \':OWNER\'\
   AND T.TABLE_NAME= :TABLE_NAME """

TAB_COMMENT_STATEMENTS_2 = """
SELECT * FROM ALL_TAB_COMMENTS T\
   WHERE T.OWNER =  %s \
   AND T.TABLE_NAME = %s  """

GET_ALL_USER_OBJ = """
  SELECT OWNER, TABLE_NAME FROM ALL_TABLES T WHERE T.OWNER = %s AND T.STATUS = 'VALID' ORDER BY TABLE_NAME ASC
"""

GET_ALL_TABLE = """
SELECT OWNER, TABLE_NAME FROM ALL_TABLES T 
WHERE T.OWNER <> 'SYS' 
ORDER BY T.OWNER ASC
"""
TABLE_DES_STATS = TABLE_DES_STATEMENTS_2
TAB_COMMENT_STATS = TAB_COMMENT_STATEMENTS_2


__all__ = ['TABLE_DES_STATS', 'TAB_COMMENT_STATS', 'GET_ALL_USER_OBJ', 'GET_ALL_TABLE']
